mod types;
use crate::runtime::client;
use crate::runtime::config::Settings;
use alloc::sync::Arc;
use anyhow::{Result, anyhow};
use rmcp::{
    ServerHandler, ServiceExt as _,
    handler::server::{router::tool::ToolRouter, wrapper::Parameters},
    tool, tool_handler, tool_router,
};
use std::sync::Mutex;
use types::{NewShellRequest, QueryRequest, SendCommandRequest, WriteKeyboardRequest};
#[derive(Clone, Debug)]
struct McpServer {
    daemon_service_name: String,
    daemon: Arc<Mutex<Option<client::DaemonClient>>>,
    tool_router: ToolRouter<Self>,
}
#[expect(
    clippy::missing_trait_methods,
    reason = "rmcp ServerHandler intentionally supplies defaults for unsupported capabilities"
)]
#[expect(
    clippy::unused_async_trait_impl,
    reason = "the async trait implementation is generated by rmcp macros"
)]
# [tool_handler (router = self . tool_router)]
impl ServerHandler for McpServer {}
# [tool_router (router = tool_router)]
impl McpServer {
    fn new(daemon_service_name: String) -> Self {
        Self {
            daemon_service_name,
            daemon: Arc::new(Mutex::new(None)),
            tool_router: Self::tool_router(),
        }
    }
    fn call(
        &self,
        request: &crate::runtime::protocol::Request,
    ) -> Result<crate::runtime::protocol::Payload> {
        let mut daemon = self.daemon.lock().map_err(|error| anyhow!("{error}"))?;
        if daemon.is_none() {
            client::ensure_daemon(&self.daemon_service_name)?;
            *daemon = Some(client::DaemonClient::connect(&self.daemon_service_name)?);
        }
        daemon
            .as_ref()
            .ok_or_else(|| anyhow!("daemon returned an unexpected response"))?
            .call(request)
    }
    #[tool(name = "new_shell", description = "打开一个新的 Shell 窗口。")]
    async fn new_shell(
        &self,
        Parameters(request): Parameters<NewShellRequest>,
    ) -> Result<String, String> {
        crate::commands::new_shell(
            |command| self.call(command),
            request.cwd_path(),
            &request.shell,
        )
        .map_err(error_text)
    }
    #[tool(
        name = "write_keyboard",
        description = "Write keyboard input bytes to the PTY master of a shell."
    )]
    async fn write_keyboard(
        &self,
        Parameters(request): Parameters<WriteKeyboardRequest>,
    ) -> Result<String, String> {
        crate::commands::write_keyboard(
            |command| self.call(command),
            request.shell_id,
            request.bytes,
        )
        .map_err(error_text)
    }
    #[tool(
        name = "send_command",
        description = "向特定 Shell 发送命令。并获得等待时间结束前该命令产生的所有输出。"
    )]
    async fn send_command(
        &self,
        Parameters(request): Parameters<SendCommandRequest>,
    ) -> Result<String, String> {
        crate::commands::send_command(
            |command| self.call(command),
            request.shell_id,
            request.command,
            request.waiting,
        )
        .map_err(error_text)
    }
    #[tool(name = "query")]
    async fn query(&self, Parameters(request): Parameters<QueryRequest>) -> Result<String, String> {
        crate::commands::query(|command| self.call(command), request.id).map_err(error_text)
    }
}
pub(crate) async fn run(settings: Settings) -> Result<()> {
    let service = McpServer::new(settings.daemon_service_name)
        .serve(rmcp::transport::stdio())
        .await?;
    service.waiting().await?;
    Ok(())
}
fn error_text(error: impl core::fmt::Display) -> String {
    error.to_string()
}
