mod types;
use crate::client;
use crate::config::Settings;
use crate::ipc::{Payload, Request};
use crate::shell::ShellChoice;
use anyhow::Result;
use base64::Engine as _;
use rmcp::{
    Json, ServerHandler, ServiceExt as _,
    handler::server::{router::tool::ToolRouter, wrapper::Parameters},
    tool, tool_handler, tool_router,
};
use types::{
    NewShellRequest, NewShellResponse, QueryRequest, QueryResponse, SendCommandRequest,
    SendCommandResponse, WriteKeyboardRequest, WriteKeyboardResponse,
};
use uuid::Uuid;
#[derive(Clone, Debug)]
struct McpServer {
    settings: Settings,
    tool_router: ToolRouter<Self>,
}
#[expect(
    clippy::missing_trait_methods,
    reason = "rmcp ServerHandler intentionally supplies defaults for unsupported capabilities"
)]
#[expect(
    clippy::unused_async_trait_impl,
    reason = "the async trait implementation is generated by rmcp macros"
)]
# [tool_handler (router = self . tool_router)]
impl ServerHandler for McpServer {}
# [tool_router (router = tool_router)]
impl McpServer {
    fn new(settings: Settings) -> Self {
        Self {
            settings,
            tool_router: Self::tool_router(),
        }
    }
    fn call(&self, request: &Request) -> Result<Payload, String> {
        client::ensure_daemon(&self.settings.daemon_address).map_err(error_text)?;
        client::call(&self.settings.daemon_address, request).map_err(error_text)
    }
    #[tool(name = "new_shell", description = "Create a new PowerShell shell.")]
    async fn new_shell(
        &self,
        Parameters(request): Parameters<NewShellRequest>,
    ) -> Result<Json<NewShellResponse>, String> {
        let shell = ShellChoice::parse(&request.shell).map_err(error_text)?;
        let payload = self.call(&Request::NewShell {
            cwd: request.cwd.into(),
            shell,
        })?;
        match payload {
            Payload::ShellCreated { shell_id } => Ok(Json(NewShellResponse::new(shell_id))),
            Payload::Pong
            | Payload::KeyboardWritten
            | Payload::CommandAccepted { .. }
            | Payload::Query(_) => Err(unexpected_daemon_response()),
        }
    }
    #[tool(
        name = "write_keyboard",
        description = "Write keyboard input bytes to the PTY master of a shell."
    )]
    async fn write_keyboard(
        &self,
        Parameters(request): Parameters<WriteKeyboardRequest>,
    ) -> Result<Json<WriteKeyboardResponse>, String> {
        let shell_id = parse_uuid(&request.shell_id)?;
        let bytes_base64 = base64::engine::general_purpose::STANDARD.encode(request.bytes);
        let payload = self.call(&Request::WriteKeyboard {
            shell_id,
            bytes_base64,
        })?;
        match payload {
            Payload::KeyboardWritten => Ok(Json(WriteKeyboardResponse::ok())),
            Payload::Pong
            | Payload::ShellCreated { .. }
            | Payload::CommandAccepted { .. }
            | Payload::Query(_) => Err(unexpected_daemon_response()),
        }
    }
    #[tool(
        name = "send_command",
        description = "Run a command in a shell and wait up to wait_ms milliseconds."
    )]
    async fn send_command(
        &self,
        Parameters(request): Parameters<SendCommandRequest>,
    ) -> Result<Json<SendCommandResponse>, String> {
        let shell_id = parse_uuid(&request.shell_id)?;
        let payload = self.call(&Request::SendCommand {
            shell_id,
            command: request.command,
            wait_ms: request.wait_ms,
        })?;
        match payload {
            Payload::CommandAccepted {
                command_id,
                end_reason,
            } => Ok(Json(SendCommandResponse::new(command_id, end_reason))),
            Payload::Pong
            | Payload::ShellCreated { .. }
            | Payload::KeyboardWritten
            | Payload::Query(_) => Err(unexpected_daemon_response()),
        }
    }
    #[tool(
        name = "query",
        description = "Query a shell screen or command output by UUID."
    )]
    async fn query(
        &self,
        Parameters(request): Parameters<QueryRequest>,
    ) -> Result<Json<QueryResponse>, String> {
        let id = parse_uuid(&request.id)?;
        let payload = self.call(&Request::Query { id })?;
        match payload {
            Payload::Query(query) => Ok(Json(query.into())),
            Payload::Pong
            | Payload::ShellCreated { .. }
            | Payload::KeyboardWritten
            | Payload::CommandAccepted { .. } => Err(unexpected_daemon_response()),
        }
    }
}
pub(crate) async fn run(settings: Settings) -> Result<()> {
    client::ensure_daemon(&settings.daemon_address)?;
    let service = McpServer::new(settings)
        .serve(rmcp::transport::stdio())
        .await?;
    service.waiting().await?;
    Ok(())
}
fn parse_uuid(value: &str) -> Result<Uuid, String> {
    Uuid::parse_str(value).map_err(error_text)
}
fn error_text(error: impl core::fmt::Display) -> String {
    error.to_string()
}
fn unexpected_daemon_response() -> String {
    "daemon returned an unexpected response".to_owned()
}
