mod types;
use crate::runtime::client;
use crate::runtime::config::Settings;
use crate::runtime::protocol::{Payload, Request};
use crate::runtime::working_dir;
use crate::shell::ShellChoice;
use alloc::sync::Arc;
use anyhow::Result;
use rmcp::{
    ServerHandler, ServiceExt as _,
    handler::server::{router::tool::ToolRouter, wrapper::Parameters},
    tool, tool_handler, tool_router,
};
use std::path::Path;
use std::sync::Mutex;
use types::{NewShellRequest, QueryRequest, SendCommandRequest, WriteKeyboardRequest};
#[derive(Clone, Debug)]
struct McpServer {
    daemon: Arc<Mutex<client::DaemonClient>>,
    tool_router: ToolRouter<Self>,
}
#[expect(
    clippy::missing_trait_methods,
    reason = "rmcp ServerHandler intentionally supplies defaults for unsupported capabilities"
)]
#[expect(
    clippy::unused_async_trait_impl,
    reason = "the async trait implementation is generated by rmcp macros"
)]
# [tool_handler (router = self . tool_router)]
impl ServerHandler for McpServer {}
# [tool_router (router = tool_router)]
impl McpServer {
    fn new(daemon: client::DaemonClient) -> Self {
        Self {
            daemon: Arc::new(Mutex::new(daemon)),
            tool_router: Self::tool_router(),
        }
    }
    fn call(&self, request: &Request) -> Result<Payload, String> {
        self.daemon
            .lock()
            .map_err(error_text)?
            .call(request)
            .map_err(error_text)
    }
    #[tool(name = "new_shell", description = "Create a new interactive shell.")]
    async fn new_shell(
        &self,
        Parameters(request): Parameters<NewShellRequest>,
    ) -> Result<String, String> {
        let shell = ShellChoice::parse(&request.shell).map_err(error_text)?;
        let cwd = request.cwd.as_deref().map(Path::new);
        let resolved_cwd = working_dir::resolve(cwd).map_err(error_text)?;
        let payload = self.call(&Request::NewShell {
            cwd: resolved_cwd,
            shell,
        })?;
        match payload {
            Payload::ShellCreated { .. } => Ok(payload.to_plain_text()),
            Payload::Pong
            | Payload::KeyboardWritten
            | Payload::CommandAccepted { .. }
            | Payload::Query(_) => Err(unexpected_daemon_response()),
        }
    }
    #[tool(
        name = "write_keyboard",
        description = "Write keyboard input bytes to the PTY master of a shell."
    )]
    async fn write_keyboard(
        &self,
        Parameters(request): Parameters<WriteKeyboardRequest>,
    ) -> Result<String, String> {
        let payload = self.call(&Request::WriteKeyboard {
            shell_id: request.shell_id,
            bytes: request.bytes,
        })?;
        match payload {
            Payload::KeyboardWritten => Ok(payload.to_plain_text()),
            Payload::Pong
            | Payload::ShellCreated { .. }
            | Payload::CommandAccepted { .. }
            | Payload::Query(_) => Err(unexpected_daemon_response()),
        }
    }
    #[tool(
        name = "send_command",
        description = "Run a command in a shell and wait up to wait_ms milliseconds."
    )]
    async fn send_command(
        &self,
        Parameters(request): Parameters<SendCommandRequest>,
    ) -> Result<String, String> {
        let payload = self.call(&Request::SendCommand {
            shell_id: request.shell_id,
            command: request.command,
            wait_ms: request.wait_ms,
        })?;
        match payload {
            Payload::CommandAccepted { .. } => Ok(payload.to_plain_text()),
            Payload::Pong
            | Payload::ShellCreated { .. }
            | Payload::KeyboardWritten
            | Payload::Query(_) => Err(unexpected_daemon_response()),
        }
    }
    #[tool(
        name = "query",
        description = "Query a shell screen or command output by ID."
    )]
    async fn query(&self, Parameters(request): Parameters<QueryRequest>) -> Result<String, String> {
        let payload = self.call(&Request::Query { id: request.id })?;
        match payload {
            Payload::Query(_) => Ok(payload.to_plain_text()),
            Payload::Pong
            | Payload::ShellCreated { .. }
            | Payload::KeyboardWritten
            | Payload::CommandAccepted { .. } => Err(unexpected_daemon_response()),
        }
    }
}
pub(crate) async fn run(settings: Settings) -> Result<()> {
    client::ensure_daemon(&settings.daemon_service_name)?;
    let daemon = client::DaemonClient::connect(&settings.daemon_service_name)?;
    let service = McpServer::new(daemon)
        .serve(rmcp::transport::stdio())
        .await?;
    service.waiting().await?;
    Ok(())
}
fn error_text(error: impl core::fmt::Display) -> String {
    error.to_string()
}
fn unexpected_daemon_response() -> String {
    "daemon returned an unexpected response".to_owned()
}
